### ISSUE TITLE
Failed to launch the browser process

### ISSUE THREAD

**Issue by MarcPinnell** [spiritix/php-chrome-html2pdf#55]
Trying to get this running and having a devil of a time. My tech and I have been through the troubleshooting steps listed, but not finding anything. Help!

Here's the error I am getting when I try to convert an HTML file:

```
Binary error: file:///home/sites.local/cattle.local/vendor/spiritix/php-chrome-html2pdf/node_modules/puppeteer/lib/esm/puppeteer/node/BrowserRunner.js:269
reject(new Error([
^

Error: Failed to launch the browser process!
../../base/allocator/partition_allocator/partition_address_space.cc(70) Check failed: false


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

at onClose (file:///home/sites.local/cattle.local/vendor/spiritix/php-chrome-html2pdf/node_modules/puppeteer/lib/esm/puppeteer/node/BrowserRunner.js:269:20)
at Interface.<anonymous> (file:///home/sites.local/cattle.local/vendor/spiritix/php-chrome-html2pdf/node_modules/puppeteer/lib/esm/puppeteer/node/BrowserRunner.js:257:24)
at Interface.emit (node:events:525:35)
at Interface.close (node:internal/readline/interface:533:10)
at Socket.onend (node:internal/readline/interface:259:10)
at Socket.emit (node:events:525:35)
at endReadableNT (node:internal/streams/readable:1359:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.14.2
```
Any ideas?

**Comment by spiritix** [comment]
Try these steps here: https://github.com/puppeteer/puppeteer/issues/6978#issuecomment-811150081

Generally, this error could also mean that there isn't enough memory available to launch Chromium.
